spring.application.name=cartecom
spring.datasource.url=jdbc:postgresql://localhost:5432/carte_commercant_db
spring.datasource.username=postgres
spring.datasource.password=azerty123.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cartecommerce67@gmail.com
spring.mail.password=zejuaaoxcijqwodz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.autoconfigure.exclude=de.codecentric.boot.admin.server.config.AdminServerNotifierAutoConfiguration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.cartecom=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE