# Files for the use of liquibase:diff.

changeLogFile=classpath:db/db.changelog-master.xml

url=jdbc:postgresql://localhost:5432/stage_db_v1
username=postgres
password=azerty123.
driver=org.postgresql.Driver


outputChangeLogFile=src/main/resources/liquibase-outputChangeLog.xml


referenceUrl=hibernate:spring:com.mc.icmc.domain?dialect=org.hibernate.dialect.PostgreSQLDialect
diffChangeLogFile=src/main/resources/db/changelog/2026/01/02-changelog.xml


